import { describe, expect, it } from "vitest";
import { isLowValueStory } from "./junk";

/**
 * Documents syndicated filler we drop from merged feeds — not real local news.
 * When adding filters, add a junk case here and a nearby "keep" case so we
 * do not over-filter human-interest stories (lottery winners, etc.).
 */
describe("isLowValueStory", () => {
  describe("filters syndicated filler", () => {
    it("drops empty titles", () => {
      expect(isLowValueStory("")).toBe(true);
      expect(isLowValueStory("   ")).toBe(true);
    });

    it("drops WTOP data-table titles", () => {
      expect(isLowValueStory("Betting Line")).toBe(true);
      expect(isLowValueStory("Sports Betting Line")).toBe(true);
      expect(isLowValueStory("Lottery")).toBe(true);
      expect(isLowValueStory("Lottery numbers")).toBe(true);
      expect(isLowValueStory("Stock quotes")).toBe(true);
    });

    it("drops WTOP lottery draw result posts", () => {
      expect(
        isLowValueStory(
          "Winning numbers drawn in Friday's Maryland Cash Pop",
          "The winning numbers in Friday's drawing of the “Maryland Cash Pop” game were:\n\nFor more lottery results, go to Jackpot.com",
        ),
      ).toBe(true);
    });

    it("drops ALXnow daily recap roundups", () => {
      expect(
        isLowValueStory(
          "ALXnow Daily Debrief for May 29, 2026",
          "Good Friday evening, Alexandria. Let's take a look back at today's stories.",
        ),
      ).toBe(true);
    });

    it("drops French Open scoreboard roundups", () => {
      expect(isLowValueStory("French Open Results")).toBe(true);
      expect(
        isLowValueStory(
          "French Open Results",
          "Novak Djokovic def. Carlos Alcaraz, 6-4, 7-6 (5)\nIga Swiatek def. Coco Gauff, 6-2, 6-1",
        ),
      ).toBe(true);
    });

    it("drops any title mentioning French Open", () => {
      expect(isLowValueStory("French Open: Djokovic advances to semifinals")).toBe(true);
    });

    it("drops betting odds grids and moneyline rows", () => {
      expect(
        isLowValueStory(
          "Today's lines",
          "FAVORITE LINE\n-110\nUNDERDOG LINE\n+105",
        ),
      ).toBe(true);

      expect(
        isLowValueStory(
          "MLB lines",
          "NFL-180 at DEN",
        ),
      ).toBe(true);

      expect(
        isLowValueStory(
          "Friday Betting Line",
          "NFL Chiefs -180 at DEN",
        ),
      ).toBe(true);
    });

    it("drops sportsbook promos", () => {
      expect(isLowValueStory("BetMGM bonus code for new users")).toBe(true);
      expect(
        isLowValueStory(
          "Special offer",
          "Use promo code WELCOME and get a first bet offer: bet $5, get $200",
        ),
      ).toBe(true);
    });

    it("drops automated earnings blurbs", () => {
      expect(isLowValueStory("Acme Corp. Fiscal Q2 Earnings Snapshot")).toBe(true);
      expect(
        isLowValueStory(
          "Company update",
          "This report was generated by Automated Insights using Zacks Investment Research.",
        ),
      ).toBe(true);
    });

    it("drops pure tennis scoreboard copy in the body", () => {
      const scoreboard = [
        "Novak Djokovic def. Carlos Alcaraz, 6-4, 7-6 (5)",
        "Iga Swiatek def. Coco Gauff, 6-2, 6-1",
        "Jannik Sinner def. Daniil Medvedev, 7-5, 6-3",
      ].join("\n");

      expect(isLowValueStory("Match updates", scoreboard)).toBe(true);
    });
  });

  describe("keeps real local news", () => {
    it("keeps lottery winner and policy stories", () => {
      expect(
        isLowValueStory(
          "Alexandria man wins $1M lottery jackpot",
          "A local resident bought the winning ticket at a convenience store on King Street.",
        ),
      ).toBe(false);

      expect(
        isLowValueStory(
          "Virginia lottery funds new school playground in Fairfax",
          "State lottery revenue will cover half the cost of the project.",
        ),
      ).toBe(false);
    });

    it("keeps ordinary local headlines", () => {
      expect(
        isLowValueStory(
          "City council approves new park in Del Ray",
          "The vote passed 6-1 after months of community meetings.",
        ),
      ).toBe(false);
    });

    it("keeps tennis-related local news that is not a scoreboard roundup", () => {
      expect(
        isLowValueStory(
          "City approves renovation of neighborhood tennis courts",
          "The project will resurface four courts at Chinquapin Park.",
        ),
      ).toBe(false);
    });
  });
});
